### ISSUE TITLE
Add source code

### ISSUE THREAD

**Issue by tarotcarrot** [BenziAhamed/Menu-Bar-Search#1]
@BenziAhamed have you considered including the source like ctwise does in his repository? That way others could submit improvements, review the code, and/or further fork the project.

**Comment by rodrigobdz** [comment]
@BenziAhamed Any word on this?

@tarotcarrot Here is the source code which was used as a base for this workflow. 
[ctwise/alfred-workflows](https://github.com/ctwise/alfred-workflows/tree/48ad9e0a59dae2631afa1ed693d71959a9dd02c7/menu-bar-search)

**Comment by BenziAhamed** [comment]
I agree with this. Will include the code.

**Comment by BenziAhamed** [comment]
Done with #2

**Comment by rodrigobdz** [comment]
Thanks!
