### ISSUE TITLE
Native Apple Silicon support

### ISSUE THREAD

**Issue by hunterliao29** [BenziAhamed/Menu-Bar-Search#10]
Hello
menu executable does not support ARM architecture.

**Comment by BenziAhamed** [comment]
I've have a M1 mac incoming soon - so I will have a better look at this.

**Comment by BenziAhamed** [comment]
Could you try downloading the updated workflow and let me know?

https://github.com/BenziAhamed/Menu-Bar-Search/blob/master/Menu%20Bar%20Search.alfredworkflow

**Comment by hunterliao29** [comment]
it worked like a charm.

**Comment by BenziAhamed** [comment]
Awesome. Closing this.
