### ISSUE TITLE
Menu unable to load after upgrade to version 1.7

### ISSUE THREAD

**Issue by XOKP** [BenziAhamed/Menu-Bar-Search#11]
I am using Big Sur on Intel iMac, the workflow doesn't work anymore after I upgraded the version to 1.7, I had to revert to 1.6 now.

**Comment by wesmoncrief** [comment]
I am having the same issue ( i just now downloaded for the first time, and get the following error -  
![Screen Shot 2021-06-28 at 11 14 08 AM](https://user-images.githubusercontent.com/16907831/123660802-f7451a00-d801-11eb-9a75-de3b9f45b800.png)

**Comment by notflip** [comment]
By not loading do you mean typing "m" doesn't trigger the plugin? This is what I'm having as well at the moment

**Comment by namnppd01894** [comment]
> I am using Big Sur on Intel iMac, the workflow doesn't work anymore after I upgraded the version to 1.7, I had to revert to 1.6 now.

Can you give me the link of 1.6 version? Thank you very much.

**Comment by matheusbaumgart** [comment]
Same issue here. Also couldn't find the link to 1.6.

**Comment by kappa4** [comment]
I found 1.6 [here](https://github.com/BenziAhamed/Menu-Bar-Search/raw/fa8569dee8fa2a105af462d31af68104255bac99/Menu%20Bar%20Search.alfredworkflow)

**Comment by dollar2048** [comment]
All versions are in the file history:
https://github.com/BenziAhamed/Menu-Bar-Search/commits/master/Menu%20Bar%20Search.alfredworkflow

**Comment by kraih** [comment]
Ran into the same issue on an Intel machine.

**Comment by jrand0m** [comment]
Same issue on intel

**Comment by ShangWangNUST** [comment]
> I am using Big Sur on Intel iMac, the workflow doesn't work anymore after I upgraded the version to 1.7, I had to revert to 1.6 now.

I have met the same issue.

**Comment by workflowsguy** [comment]
The issue is caused by the fact that the included `menu`binary is compiled for "arm64" arhitecture only instead of both this and "x86_64". So it won't work on Macs with Intel CPUs. 😞

**Comment by chrismessina** [comment]
> The issue is caused by the fact that the included `menu`binary is compiled for "arm64" architecture only instead of both this and "x86_64". So it won't work on Macs with Intel CPUs. 😞

What would it take to get a binary compiled for both architectures?

**Comment by BenziAhamed** [comment]
Kindly download the version 1.8 and let me know if this is sorted. [View v1.8 worlflow](https://github.com/BenziAhamed/Menu-Bar-Search/blob/ac77d01c6b4ef30c4acd02e075cc2068ffd827ad/Menu%20Bar%20Search.alfredworkflow)

**Comment by chrismessina** [comment]
> Kindly download the version 1.8 and let me know if this is sorted. [View v1.8 worlflow](https://github.com/BenziAhamed/Menu-Bar-Search/blob/ac77d01c6b4ef30c4acd02e075cc2068ffd827ad/Menu%20Bar%20Search.alfredworkflow)

Woohoo! Seems to work! 
![bitmoji](https://sdk.bitmoji.com/render/panel/17214cec-3a6c-478a-a7bf-17ba4cf5b00c-dcb126b9-05d1-4f72-89a8-86673e617068-v1.png?transparent=1&palette=1&width=246)
