### ISSUE TITLE
1.6 not working at m1 / 1.7 not working at intel mac 

### ISSUE THREAD

**Issue by Korean-David** [BenziAhamed/Menu-Bar-Search#13]
The 1.7 version is not working at my intel mac, so I had to install the 1.6 version.
But the 1.6 version is not working at my m1.

**Comment by meta** [comment]
can confirm on `OS: macOS 11.6 20G165 x86_64`
<img width="841" alt="alfred-menu-search-bug" src="https://user-images.githubusercontent.com/5732757/140461563-2c58a319-fb1f-4e62-90b3-c10f04e46ac3.png">

**Comment by gnestor** [comment]
Duplicate of https://github.com/BenziAhamed/Menu-Bar-Search/issues/11

**Comment by alexbarton** [comment]
It would be really great to have a universal build, working on both Intel and M1 Macs – I sync my Alfred settings between machines (_because Alfred is that great! 😉_), and right now either one or the other machine is "broken" as v1.6 works on Intel only and v1.7 works on M1 only …

**Comment by BenziAhamed** [comment]
Kindly download the version 1.8 and let me know if this is sorted. [View v1.8 worlflow](https://github.com/BenziAhamed/Menu-Bar-Search/blob/ac77d01c6b4ef30c4acd02e075cc2068ffd827ad/Menu%20Bar%20Search.alfredworkflow)

**Comment by alexbarton** [comment]
Thanks a lot @BenziAhamed! I can confirm it working on M1, will test Intel on Monday and report back.
Again: Thank you!

**Comment by alexbarton** [comment]
And now I can confirm that v1.8 is working on both my Intel MacBook Pro as well as my M1 Mac mini – cool, very good! Thanks a lot, great work!
