### ISSUE TITLE
[Feature Request] Update Notifier?

### ISSUE THREAD

**Issue by iandol** [BenziAhamed/Menu-Bar-Search#19]
Hi, first off thank you for a **most** excellent workflow!!!!!

I wondered if you had thought of adding an update notifier or auto-update mechanism? I know of at least @vitorgalvao's OneUpdater: https://github.com/vitorgalvao/alfred-workflows

**Comment by vitorgalvao** [comment]
[We’re discussing](https://www.alfredforum.com/topic/19183-menu-bar-search/) the inclusion of this workflow [in the Alfred Gallery](https://www.alfredforum.com/topic/19058-submitting-workflows-for-the-alfred-gallery/) and for that it cannot have an internal updater. This is to avoid a confusing interaction of crossed updates (Alfred itself will check for them) *and* for security reasons, as Gallery workflows go through a number of checks.

**Comment by iandol** [comment]
Oh gosh, that is even better!!!!! ❤️ This workflow definitely deserves being featured, as it really improves accessibility and the reach of Alfred into running apps...

I'll close this as it seems @BenziAhamed is dealing with this...
