### ISSUE TITLE
Issue in macOS 13.1

### ISSUE THREAD

**Issue by helicos6** [BenziAhamed/Menu-Bar-Search#20]
Has this workflow been abandoned?

![image](https://user-images.githubusercontent.com/34452093/208699709-7a72110e-1f98-458f-9981-0dd9170c6f0b.png)

**Comment by BenziAhamed** [comment]
No it hasn't been abandoned. See #4 for workarounds.

**Comment by helicos6** [comment]
@BenziAhamed I went to Settings > Security and select Allow menu. It's working now. Thank you.
