### ISSUE TITLE
Notarise command line app so that we can add this to Alfred Workflow gallery

### ISSUE THREAD

**Issue by BenziAhamed** [BenziAhamed/Menu-Bar-Search#21]

**Comment by xilopaint** [comment]
Any news here @BenziAhamed? Looking forward to seeing this workflow in the Gallery.

**Comment by BenziAhamed** [comment]
In progress at the moment - there is a minor glitch with my Apple Developer account setup that prevents Xcode (and my dev mac) from being able to recognise my account; I have been trying to sort it out with Developer Support - hopefully should get resolved soon! And I can (finally) notarise the tool.

**Comment by Ptujec** [comment]
If it does not work out you could take a look at [Roeys](https://github.com/roeybiran) [CLI](https://www.roeybiran.com/apps/finbar/help), which he created for [Finbar](https://www.roeybiran.com/apps/finbar). I'm using it in my [LaunchBar action](https://github.com/Ptujec/LaunchBar/tree/master/Menu-Bar#readme). It works great. And he is working on further optimizing it.

**Comment by BenziAhamed** [comment]
@xilopaint appreciate it if you could give v2.0 a try and see if the notarized version works: https://github.com/BenziAhamed/Menu-Bar-Search/releases

**Comment by xilopaint** [comment]
It works for me! Thanks for the improvements. This is easily one of Alfred's best workflows and most productive tools I use.

**Comment by BenziAhamed** [comment]
You can now search for and download the workflow from the [Alfred Workflow Gallery](https://alfred.app/workflows/benziahamed/menu-bar-search/).
