### ISSUE TITLE
[FR] The option to disable the menu and sub-menu to makes it not included in the results

### ISSUE THREAD

**Issue by ghost** [BenziAhamed/Menu-Bar-Search#23]
When I search for something on the browser menu, the results include history and bookmarks. Can you create a feature where I can disable some menus that I don't want to show up in the results?

Hope to hear from you soon
Thank you very much

**Comment by BenziAhamed** [comment]
You can do that already! It wasn't well documented, so here a wiki page about [per app customization](../wiki/Per-app-search-customization).

Please have a look and follow the steps there to see if it works for you.

**Comment by ghost** [comment]
> You can do that already! It wasn't well documented, so here a wiki page about [per app customization](../wiki/Per-app-search-customization).
> 
> Please have a look and follow the steps there to see if it works for you.

Thank you. But it not work. Can you please check where did i miss?

<img width="400" alt="CleanShot 2023-03-30 at 08 53 51@2x" src="https://user-images.githubusercontent.com/61721378/228707986-fed02cd5-2a1e-4f73-a0c9-e35f4442e1a7.png">
<img width="715" alt="CleanShot 2023-03-30 at 08 53 34@2x" src="https://user-images.githubusercontent.com/61721378/228707997-bbc84152-b814-4f06-a06f-7975ac895ea1.png">

**Comment by BenziAhamed** [comment]
- Can you try changing the spelling of `Favourites` to `Favorites`?
- Does it work for the `History` menu?

**Comment by ghost** [comment]
It worked. My bad. Thank you very much.

**Comment by chumido** [comment]
@BenziAhamed Hi. Can you add an feature that i can change the directory of setting folder?
