### ISSUE TITLE
Doesn't work with Airmail

### ISSUE THREAD

**Issue by manishie** [BenziAhamed/Menu-Bar-Search#3]
Great workflow!  I'm running AirMail mac v 3.6.71 and the menus are incomplete.  Some of the menus are available (e.g. "About Airmail") but others aren't (e.g. anything in the Messages menu like "Get Mail" or "Forward").  Thanks!

**Comment by BenziAhamed** [comment]
Thanks.

I don't have Airmail installed, but there is a limit of 40 sub-menu items it will display (mainly done for speed). 

If your "Forward" menu has a lot of sub-menu items under it, it will not display them. I'm not sure if that is the exact problem here though.

I will try to check this out later.

**Comment by manishie** [comment]
Thanks!  The messages menu has about 20 main items, one of which is "Forward".  "Forward" itself does not have any sub-menu items.   But there are other items in the Messages menu which do have submenu items, so maybe those are overloading it?

**Comment by manishie** [comment]
Any idea why this isn't working?  There aren't a lot of items in that menu.  
![image](https://user-images.githubusercontent.com/939983/82693502-87d02480-9c16-11ea-8229-a3985da91e89.png)

**Comment by BenziAhamed** [comment]
@manishie well I finally installed airmail. Let me see if I can find out why it is not working.

**Comment by manishie** [comment]
Thanks!


From: Benzi <notifications@github.com> <notifications@github.com>
Reply: BenziAhamed/Menu-Bar-Search
<reply@reply.github.com>
<reply@reply.github.com>
Date: May 28, 2020 at 7:23:27 AM
To: BenziAhamed/Menu-Bar-Search <menu-bar-search@noreply.github.com>
<menu-bar-search@noreply.github.com>
Cc: manish mukherjee <manishie@manishie.com> <manishie@manishie.com>,
Mention <mention@noreply.github.com> <mention@noreply.github.com>
Subject:  Re: [BenziAhamed/Menu-Bar-Search] Doesn't work with Airmail (#3)

@manishie <https://github.com/manishie> well I finally installed airmail.
Let me see if I can find out why it is not working.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/BenziAhamed/Menu-Bar-Search/issues/3#issuecomment-635381416>,
or unsubscribe

**Comment by manishie** [comment]
I don't use Airmail anymore.  :-)
