### ISSUE TITLE
No Longer Working on macOS Catalina

### ISSUE THREAD

**Issue by wujunchuan** [BenziAhamed/Menu-Bar-Search#4]
With the release of macOS Catalina, 32-bit app support is no longer available, which means many of your older apps will no longer work if they haven't been updated to 64-bit.

![image](https://user-images.githubusercontent.com/7511631/66372887-c8f22c00-e9d9-11e9-9baa-7ac7295a6970.png)

![image](https://user-images.githubusercontent.com/7511631/66372927-e1624680-e9d9-11e9-841a-230680049924.png)

**Comment by AleksIralda** [comment]
I Confirm this...
![Screen Shot 2019-10-09 at 15 59 28](https://user-images.githubusercontent.com/10256929/66519926-cc56e780-eaad-11e9-9e7b-615f5d8098ca.png)

**Comment by wujunchuan** [comment]
Following @AleksIralda  that message is says "This software needs to be updated. Contact the developer for more information."

Well, this is not 64-bit problems. Just **Right click and click open** again

![1](https://user-images.githubusercontent.com/7511631/66534348-856a0000-eb48-11e9-87e0-8203005f8c69.png)

And then 

![2](https://user-images.githubusercontent.com/7511631/66534356-8ac74a80-eb48-11e9-9fea-d1ce1632c4af.png)



Ref: https://www.reddit.com/r/MacOS/comments/cgj1qs/cant_be_opened_because_apple_cannot_check_it_for/
