### ISSUE TITLE
Diacritic insensitive search

### ISSUE THREAD

**Issue by gennaios** [BenziAhamed/Menu-Bar-Search#6]
Hello,

For those using macOS with a different language, it would be nice to filter menu results with a diacritic insensitive search.

**Comment by BenziAhamed** [comment]
Not packaged the workflow yet as a new release, but this will be available in v2.0.

https://github.com/BenziAhamed/Menu-Bar-Search/commit/26cc7520cb1c09cd53e3ea324603bacfe0fe7d3b adds support for this.

**Comment by BenziAhamed** [comment]
This should now work by default in [v2.0](https://github.com/BenziAhamed/Menu-Bar-Search/releases/download/v2.0/Menu.Bar.Search.alfredworkflow). Closing this.
